
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE 'CREATE USER HR IDENTIFIED BY HR';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO HR';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO HR';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO HR';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO HR';
    
END;