
BEGIN
    EXECUTE IMMEDIATE 'ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE';
    EXECUTE IMMEDIATE 'CREATE USER CO IDENTIFIED BY CO';
    EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO CO';
    EXECUTE IMMEDIATE 'GRANT CONNECT TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE MATERIALIZED VIEW TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE TYPE TO CO';
    EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO CO';
    EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO CO';
    
END;